### ISSUE TITLE
What is the extension of the files placed in collection folder?

### ISSUE THREAD

**Issue by raviraj-s** [cry/nbp#4]
I have hosted the downloaded nbp on IIS, but IIS is not able to read files placed in the collection folder. I changed the extension to ".txt" and got it working, but the behavior is a little weird. 
For example:
In website (https://cry.github.io/nbp/)
"Monday@1200" is not a common password.
In hosted website (downloaded version)
"Monday@1200" is a common password.

**Comment by cry** [comment]
Sorry this project is no longer maintained and I'm unsure of why you're having the problem you're having. It looks like the data is being interpreted weirdly or that the bloom filter is acting up.
